# PostgreSQL Database Configuration
# Hosting par ye variables dashboard se set honge
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolio_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Admin Security Credentials
portfolio.admin.username=${ADMIN_USERNAME:admin}
portfolio.admin.password=${ADMIN_PASS:Harsh@7310}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server.port=${PORT:8080}
